// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectGadai.API.Data;

#nullable disable

namespace ProjectGadai.API.Migrations
{
    [DbContext(typeof(ProjectGadaiDbContext))]
    [Migration("20230121104818_pelanggan migration")]
    partial class pelangganmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectGadai.API.Models.Pelanggan", b =>
                {
                    b.Property<string>("id_pelanggan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("jenis_usaha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kelamain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maks_transaksi")
                        .HasColumnType("int");

                    b.Property<string>("nama_pelanggan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomor_hp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomor_ktp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_pelanggan");

                    b.ToTable("Pelanggans");
                });

            modelBuilder.Entity("ProjectGadai.API.Models.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maks_transaksi")
                        .HasColumnType("int");

                    b.Property<string>("nama_user")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomor_hp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tanggal_masuk")
                        .HasColumnType("datetime2");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
